name: "Cron Job to regenerate Readme every 24 hours"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go executable
        run: go build -o main main.go

      - name: Generate Readme
        run: ./main

      - name: Commit and Push changes
        run: |
          git config --local user.email "41448663+BRAVO68WEB@users.noreply.github.com"
          git config --local user.name "BRAVO68WEB"
          git add README.md
          git commit -m "Regenerated Readme" || echo "No changes to commit"
          git push