name: Daily Go Script Run

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-daily-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go executable
        run: go build main.go

      - name: Run the Go script
        run: ./main
